server:
  port: 8081

spring.cloud.vault:
    host: vault.vieslocal.com
    port: 443
    scheme: https
    uri: https://vault.vieslocal.com
    connection-timeout: 5000
    read-timeout: 15000
spring.config.import: vault://v_eco/authenticator/test